public enum Estado {RETA,ESQUERDA,DIREITA,PARAR,SENSOR,DISTANCIA,DORMIR,CONFIGURACAO,ESCOLHA,DESACTIVAR,ACCAO,OBSTACULO,TERMINAR,LIGAR,COMUNICACAO,VAGUEAR,SEGUIR,ESPERA,DISTANCIA_VAGUEAR,DISTANCIA_SEGUIR,EVITAR,DORMIR_RETA,DORMIR_AJUSTE,MEDIR_D0,MEDIR_D1};

